### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by stefanwitkamp** [athombv/com.wemo#5]
After a while (no direct source found - could be one) app chrashes.

Crash log:

```

Stack trace:

Error: HTTP 400: <html><body><h1>400 Bad Request</h1></body></html>
at IncomingMessage.<anonymous> (/node_modules/wemo-client/client.js:69:12)
at emitNone (events.js:72:20)
at IncomingMessage.emit (events.js:166:7)
at endReadableNT (_stream_readable.js:921:12)
at nextTickCallbackWith2Args (node.js:442:9)
at process._tickCallback (node.js:356:17)

Exit code: 1
```

**Comment by BasKiers** [comment]
This crash should now be fixed
