### ISSUE TITLE
Can not subscribe without callbackURL

### ISSUE THREAD

**Issue by mbardelmeijer** [athombv/com.wemo#6]
Worked a couple of times, but after 2/3 times, the application crashes. I'm using a single WeMo switch.

Stacktrace:
```
Error: Can not subscribe without callbackURL
at WemoClient._subscribe (/node_modules/wemo-client/client.js:286:11)
at ontimeout [as _onTimeout] (timers.js:195:34)
at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by BasKiers** [comment]
Hi,

This should be fixed as of v2.1.7. Please open a new issue if you encounter more crashes/bugs.
