### ISSUE TITLE
Crash after latest update...

### ISSUE THREAD

**Issue by markaswift** [athombv/com.wemo#7]
The app crashes regularly after the latest update, further on restart I see no value from my insight plugs.

```
Stack trace:

Error: Can not subscribe without callbackURL
at WemoClient._subscribe (/node_modules/wemo-client/client.js:286:11)
at ontimeout [as _onTimeout] (timers.js:195:34)
at Timer.listOnTimeout (timers.js:92:15)

Exit code: 1
Exit signal: null
```

**Comment by BasKiers** [comment]
Yes, I reintroduced this bug. I fixed this in 2.1.7 just now.
